snipcart/snipcart-l10n

- locales/en.json
- locales/fr.json
> Payment Form localization #169954464

- locales/sv.json
Created a new localization file for Swedish. I am from Sweden and looking forward to using Snipcart in my new store!
> Translated and added file for Swedish

- locales/es.json
Spanish Locale (es), Keep up the great  work!
> Added Spanish Locale

- locales/da.json
Added localization file for Danish
> Added localization file for Danish

- locales/ro.json
> Added Romanian language

- locales/zh-TW.json
I added the new locale, `zh-TW`. There are fields still in English, but it is okay. I left them in English purposely. Those English words are commonly used in people using and speaking in the Traditional Chinese region/area.
> :globe_with_meridians: (zh) added new locale zh-TW

- locales/ru.json
> Added Russian locale

- locales/fr.json
- marchand et pas marchant
- assistance et pas assitance
> Corrections de quelques fautes

- locales/ar.json
> Arabic locale

- locales/zh-TW.json
- update wordings and fix typos
> [3.0.12] (zh) update wordings and fix typos

- locales/de-CH.json
- locales/de-ch.json
Formal German address.
Swiss specific denomination of province (= "Kanton")
> German Translation file - all available fields translated

- locales/fr.json
Quantités: https://fr.wiktionary.org/wiki/quantit%C3%A9
> [3.0.14] Fixing typos and use proper ellipsis

- locales/zh.json
Hello again!
The `zh` locale has been updated.
> chore(locales): update zh locales

- locales/de.json
I added the newest variables from the en.json to the de.json file. 
Not sure about the translation of "yes_use_it", but i think short is better than full translated. :)
> [3.0.21] feat(de): update german translation files with current english variables

- locales/fr.json
Add missing payment translations (deffered payment & methods)
> [3.0.21] Add french translations for payment

- locales/zh-TW.json
- locales/zh.json
> [3.0.21] update zh

- locales/uz.json
> [3.0.21] New language  add

- locales/pl.json
Hi
I wrote polish translations, check them out. I would be easier for me to see them live within Snipcart to see what I should correct.
Cheers
> .pl translations

- .gitignore
- locales/zh-TW.json
- locales/zh.json
- add subscriptions localization
> :globe_with_meridians: (zh) add subscriptions localization

- locales/lt.json
Created Lithuanian translation in lt.json file based on the English version.
> Added Lithuanian locale translation

- locales/en.json
https://www.pivotaltracker.com/story/show/169768302
https://www.pivotaltracker.com/story/show/169768362
> Changed some strings in change password form, edit customer address form and customer details card

- locales/en.json
"I don’t see my address" -> "I can’t find my address"
> EN: update address_form.dont_see_address

- locales/zh-TW.json
- locales/zh.json
> update zh to lastest locale

- locales/nl.json
Added keys and translated them into dutch language
> Updated nl.json

- locales/zh-CN.json
- locales/zh-TW.json
- locales/zh-hk.json
- locales/zh.json
> fix typo and update wording on all zh locales

- locales/hr.json
Added translation for missing "taxes" key in "cart_summary".
> Updated translation for the Croatian language

- locales/sv.json
Fixed indentation and added translation for missing strings.
> Updating swedish translation.

- locales/en-GB.json
Added the en-GB locale, the missing locale was causing errors for me. Updated with common British terms too.
> Add en-GB locale

- locales/lt.json
Added a new lt locale translation for view_detailed_cart.
Fixed 2 other previous translations.
> add to cart fix

- locales/en.json
- locales/fr.json
Allows all countries and states to be localized.
> Add countries and states to EN locale

- locales/it.json
Hello,
I've updated the "it" locale 😀
Note: I only skipped the translation of "placed_on" (line 48) because I'm not sure about it.
Do you mean something like "placed on hold", "order placed on our online shop" or something like "order placed on December 7th"?
> Update it.json locale

- locales/en.json
Linked to [Color Theme - Part 3](https://github.com/snipcart/snipcart-theme-vue/pull/327).
I think it will be useful later on to have default fallbacks for some phrases.
> Add default phrases

- locales/zh-CN.json
Hello there. Our Chinese team updated your Simplified Chinese internationalization. They also suggested that you should make Simplified Chinese (zh-CN.json) as default. Your current default is Traditional Chinese (zh.json). Almost everyone use Simplified Chinese as default. I didn't want to change the content from zh-CN.json to zh.json in this PR, I just wanted to let you know so you can do it yourself it you find it convinient.
> Updating Simplified Chinese

- locales/en-AU.json
created en-AU translation (Australian English)
> fix: create en-AU translation

- locales/ro.json
i have added more available fields and updated the translation to be more
- polite / neutral
i believe this would make it look more professional instead of using friendly tone in the sentences
> added more fields and update translation

- build.js
- locales/en-AU.json
- locales/ro.json
Fixes a formatting issue introduced in https://github.com/snipcart/snipcart-l10n/pull/131 that I didn't notice before merging.
Edit: also fixes https://github.com/snipcart/snipcart-l10n/pull/130 and I added a log line which will tell what lang failed to parse inside the build logs.
> Fixed ro.json formatting

- locales/it.json
Hello!
I've updated the "it" locale  👋😀
> Update it.json (and countries)

- locales/sk.json
Slovak country names sourced from https://sk.wikipedia.org/wiki/ISO_3166-1
> Add countries to sk.json

- locales/sl.json
This locale is kinda urgent for me, I would be very grateful for a quick review & merge. 
Thank you
> Add the slovenian locale

- locales/hu.json
Updated the hungarian locale, added country names also!
> Updated hu.json

- locales/pt-BR.json
Updated pt-BR locale with all the new additions since the last time this file was changed.
> Update pt-BR locale with the new translations

- locales/en.json
added methods object inside shipping to enable shipping method localization.
> added methods object inside shipping

- locales/ja.json
Some improvements to the language used in the address_form for Japanese
> Adjustments to address_form Japanese

- locales/es.json
Country names where missing the "name" label, resulting in wrong display at the shipping section of the cart.
> ES country names were missing "name" label.

- locales/nl.json
I added the phone key and value for Dutch (nl)
> Add Phone key in Nl
